name: 🚀 Deploy CI theme on Develop Server

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  web-deploy:
    name: 🎉 Build Project and Send to FTP
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 🔨 Use Node.js 16
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16"

      - name: 🚧 Build Project
        run: |
          yarn
          npm run build
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          password: ${{ secrets.DEV_PASS }}
          server-dir: ${{ secrets.DEV_PATH }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.idea/**
            **/.budfiles/**
            **/.idea/**